CREATE TABLE IF NOT EXISTS cron_settings (
  name TEXT PRIMARY KEY,
  cron TEXT,
  interval_minutes INT NOT NULL DEFAULT 60,
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  run_on_startup BOOLEAN NOT NULL DEFAULT FALSE,
  meta JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE cron_settings
  ADD COLUMN IF NOT EXISTS cron TEXT;

ALTER TABLE cron_settings
  ADD COLUMN IF NOT EXISTS interval_minutes INT NOT NULL DEFAULT 60;

ALTER TABLE cron_settings
  ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE cron_settings
  ADD COLUMN IF NOT EXISTS run_on_startup BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE cron_settings
  ADD COLUMN IF NOT EXISTS meta JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE cron_settings
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
